# Generated by Django 2.1.4 on 2018-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_Title', models.CharField(max_length=50)),
                ('contract_Doc_File', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
